name: Publish to npm

on:
  push:
    tags:
      - 'v*'
      - 'V*'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org/'

      - name: Install dependencies
        run: npm install

      - name: Create .env file from secrets
        run: |
          echo "BACKEND_URL=${{ secrets.BACKEND_URL }}" >> .env
          echo "CALLBACK_URL=${{ secrets.CALLBACK_URL }}" >> .env
          echo "DNS_CREATE_URL=${{ secrets.DNS_CREATE_URL }}" >> .env
          echo "SERVER_CREATE_URL=${{ secrets.SERVER_CREATE_URL }}" >> .env
          echo "SERVER_STATUS_URL=${{ secrets.SERVER_STATUS_URL }}" >> .env

      - name: Build binaries
        run: npm run build

      - name: Upload binaries as artifact
        uses: actions/upload-artifact@v4
        with:
          name: mineflared-binaries
          path: npm-wrapper/bin/

      - name: Publish to npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish

