name: Publish to npm

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org/'

      - name: Install dependencies
        run: |
          cd npm-wrapper
          npm install
          cd ..

      - name: Build binaries
        run: node npm-wrapper/build.js

      - name: Upload binaries as artifact
        uses: actions/upload-artifact@v4
        with:
          name: mineflared-binaries
          path: npm-wrapper/bin/

      - name: Move npm-wrapper contents to root
        run: |
          rsync -a --remove-source-files npm-wrapper/ . && rm -r npm-wrapper

      - name: Publish to npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish
